# Site settings
title: Things you should know about Web Development 
email: acuevas.15@gmail.com 
description: "Yet another blog about Web Development."
baseurl: ""
url: "http://yourdomain.com"
github_username: acuevas-15 
twitter_username: acuevas_15 

author:
  home: "Columbus, Ohio"
# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
